global:
  scrape_interval: 15s  # Frecuencia con la que se recopilan las métricas

scrape_configs:
  - job_name: 'mi_aplicacion'
    static_configs:
      - targets: ['localhost:9090']  # Endpoint donde tu aplicación expone métricas
